import { useEffect } from 'react'
import { createBrowserRouter, RouterProvider } from 'react-router-dom'
import { Toaster } from 'sonner'
import { useAppDispatch } from './app/hooks'
import { NetworkBanner } from './components/NetworkBanner'
import { AdminRoute, ProtectedRoute } from './components/RouteGuards'
import { restoreSession, sessionExpired, tokenRefreshed } from './features/auth/authSlice'
import { AdminLayout } from './layouts/AdminLayout'
import { StoreLayout } from './layouts/StoreLayout'
import { AccountPage } from './pages/AccountPage'
import { AuthPage } from './pages/AuthPage'
import { CartPage } from './pages/CartPage'
import { CheckoutPage } from './pages/CheckoutPage'
import { CheckoutSuccessPage } from './pages/CheckoutSuccessPage'
import { HomePage } from './pages/HomePage'
import { OrderDetailPage } from './pages/OrderDetailPage'
import { OrdersPage } from './pages/OrdersPage'
import { ProductDetailPage } from './pages/ProductDetailPage'
import { ProductsPage } from './pages/ProductsPage'
import { DashboardPage } from './pages/admin/DashboardPage'
import { OrdersAdminPage } from './pages/admin/OrdersAdminPage'
import { ProductsAdminPage } from './pages/admin/ProductsAdminPage'
import { UsersAdminPage } from './pages/admin/UsersAdminPage'
const router=createBrowserRouter([{element:<StoreLayout/>,children:[{path:'/',element:<HomePage/>},{path:'/products',element:<ProductsPage/>},{path:'/products/:id',element:<ProductDetailPage/>},{path:'/cart',element:<CartPage/>},{path:'/login',element:<AuthPage mode="login"/>},{path:'/register',element:<AuthPage mode="register"/>},{element:<ProtectedRoute/>,children:[{path:'/checkout',element:<CheckoutPage/>},{path:'/checkout/success',element:<CheckoutSuccessPage/>},{path:'/orders',element:<OrdersPage/>},{path:'/orders/:id',element:<OrderDetailPage/>},{path:'/account',element:<AccountPage/>}]}]},{element:<AdminRoute/>,children:[{path:'/admin',element:<AdminLayout/>,children:[{index:true,element:<DashboardPage/>},{path:'products',element:<ProductsAdminPage/>},{path:'orders',element:<OrdersAdminPage/>},{path:'users',element:<UsersAdminPage/>}]}]},{path:'*',element:<div className="grid min-h-screen place-items-center text-center"><div><h1 className="text-7xl font-black">404</h1><a href="/" className="btn-primary mt-5">Back home</a></div></div>}])
export default function App(){const dispatch=useAppDispatch();useEffect(()=>{dispatch(restoreSession());const expired=()=>dispatch(sessionExpired());const refreshed=(e:Event)=>dispatch(tokenRefreshed((e as CustomEvent<string>).detail));window.addEventListener('auth:expired',expired);window.addEventListener('auth:refreshed',refreshed);return()=>{window.removeEventListener('auth:expired',expired);window.removeEventListener('auth:refreshed',refreshed)}},[dispatch]);return <><RouterProvider router={router}/><NetworkBanner/><Toaster richColors closeButton position="top-right"/></>}
