import { ArrowRight } from 'lucide-react'
import { useState } from 'react'
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom'
import { toast } from 'sonner'
import { errorMessage } from '../api/client'
import { useAppDispatch, useAppSelector } from '../app/hooks'
import { login, register } from '../features/auth/authSlice'
export function AuthPage({ mode }: { mode: 'login' | 'register' }) {
  const [form, setForm] = useState({ name: '', email: '', password: '' }); const [error, setError] = useState(''); const { user, loading } = useAppSelector((s) => s.auth); const dispatch = useAppDispatch(); const navigate = useNavigate(); const location = useLocation()
  if (user) return <Navigate to="/" replace/>
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setError(''); try { if (mode === 'login') await dispatch(login({ email: form.email, password: form.password })).unwrap(); else await dispatch(register(form)).unwrap(); toast.success(mode === 'login' ? 'Welcome back' : 'Account created'); navigate((location.state as { from?: { pathname: string } })?.from?.pathname || '/') } catch (err) { setError(errorMessage(err)) } }
  return <div className="container-app grid min-h-[70vh] place-items-center py-12"><div className="w-full max-w-md rounded-3xl bg-white p-7 shadow-xl ring-1 ring-black/5 sm:p-10"><p className="text-xs font-bold uppercase tracking-[.2em] text-forest">{mode === 'login' ? 'Welcome back' : 'Join the nook'}</p><h1 className="mt-2 text-3xl font-black">{mode === 'login' ? 'Sign in to continue' : 'Create your account'}</h1><p className="mt-2 text-sm text-black/50">{mode === 'login' ? 'Track orders and enjoy a faster checkout.' : 'Save your details, bag, and order history.'}</p>{error && <div className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}{mode === 'login' && <div className="mt-5 rounded-xl bg-mint/60 p-3 text-sm"><p className="font-semibold text-forest">Demo accounts</p><div className="mt-2 flex flex-wrap gap-2"><button type="button" className="rounded-full bg-white px-3 py-1.5 text-xs font-semibold shadow-sm" onClick={() => setForm({ name: '', email: 'maya@nook.test', password: 'Customer123!' })}>Use customer</button><button type="button" className="rounded-full bg-white px-3 py-1.5 text-xs font-semibold shadow-sm" onClick={() => setForm({ name: '', email: 'admin@nook.test', password: 'Admin123!' })}>Use admin</button></div></div>}<form onSubmit={submit} className="mt-7 space-y-4">{mode === 'register' && <label><span className="label">Full name</span><input className="field" required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })}/></label>}<label><span className="label">Email address</span><input className="field" type="email" required value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })}/></label><label><span className="label">Password</span><input className="field" type="password" minLength={8} required value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })}/></label><button disabled={loading} className="btn-primary mt-2 w-full">{loading ? 'Please wait…' : mode === 'login' ? 'Sign in' : 'Create account'} <ArrowRight size={17}/></button></form><p className="mt-6 text-center text-sm text-black/50">{mode === 'login' ? "Don't have an account? " : 'Already have an account? '}<Link className="font-bold text-forest" to={mode === 'login' ? '/register' : '/login'}>{mode === 'login' ? 'Sign up' : 'Sign in'}</Link></p></div></div>
}
