import { Minus, Plus, Trash2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useAppDispatch, useAppSelector } from '../app/hooks'
import { EmptyState } from '../components/EmptyState'
import { removeFromCart, updateQuantity } from '../features/cart/cartSlice'
import { money } from '../utils/format'
import { mediaUrl } from '../utils/media'
export function CartPage() {
  const items = useAppSelector((s) => s.cart.items); const dispatch = useAppDispatch(); const subtotal = items.reduce((sum, i) => sum + i.product.price * i.quantity, 0)
  if (!items.length) return <div className="container-app py-14"><EmptyState title="Your bag is empty" text="Good things are waiting. Browse the collection and find something you love." action={<Link className="btn-primary" to="/products">Start shopping</Link>}/></div>
  return <div className="container-app py-10"><h1 className="mb-8 text-4xl font-black tracking-tight">Your bag <span className="text-black/25">({items.length})</span></h1><div className="grid gap-8 lg:grid-cols-[1fr_380px]"><div className="card divide-y divide-black/5 px-5">{items.map(({ product, quantity }) => <div key={product._id} className="flex gap-4 py-5"><Link to={`/products/${product.slug}`} className="size-24 shrink-0 overflow-hidden rounded-xl bg-cream">{product.images[0] && <img className="h-full w-full object-cover" src={mediaUrl(product.images[0].url)}/>}</Link><div className="min-w-0 flex-1"><Link to={`/products/${product.slug}`} className="font-bold">{product.name}</Link><p className="mt-1 text-sm text-black/45">{product.category.name}</p><div className="mt-4 flex items-center justify-between"><div className="flex items-center rounded-full border border-black/10"><button className="p-2" onClick={() => dispatch(updateQuantity({ id: product._id, quantity: quantity - 1 }))}><Minus size={14}/></button><span className="w-7 text-center text-xs font-bold">{quantity}</span><button className="p-2" onClick={() => dispatch(updateQuantity({ id: product._id, quantity: quantity + 1 }))}><Plus size={14}/></button></div><button className="text-black/35 hover:text-red-600" onClick={() => dispatch(removeFromCart(product._id))}><Trash2 size={18}/></button></div></div><b>{money(product.price * quantity)}</b></div>)}</div><aside className="card h-fit p-6"><h2 className="text-xl font-bold">Order summary</h2><div className="mt-6 space-y-3 text-sm"><div className="flex justify-between text-black/55"><span>Subtotal</span><span>{money(subtotal)}</span></div><div className="flex justify-between text-black/55"><span>Shipping</span><span>Free</span></div><div className="flex justify-between border-t border-black/8 pt-4 text-lg font-bold"><span>Total</span><span>{money(subtotal)}</span></div></div><Link to="/checkout" className="btn-primary mt-6 w-full">Continue to checkout</Link><p className="mt-3 text-center text-xs text-black/40">Taxes calculated where applicable</p></aside></div></div>
}
