import { Edit3, Plus, Search, Trash2, X } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { toast } from 'sonner'
import { api, errorMessage } from '../../api/client'
import { Pagination } from '../../components/Pagination'
import type { ApiResponse, Category, Pagination as PaginationType, Product } from '../../types'
import { money } from '../../utils/format'
import { mediaUrl } from '../../utils/media'
type Form = { name:string;description:string;price:string;compareAtPrice:string;stock:string;category:string;images:FileList|null }
const blank:Form={name:'',description:'',price:'',compareAtPrice:'',stock:'0',category:'',images:null}
export function ProductsAdminPage(){const [products,setProducts]=useState<Product[]>([]);const [categories,setCategories]=useState<Category[]>([]);const [pagination,setPagination]=useState<PaginationType>();const [page,setPage]=useState(1);const [search,setSearch]=useState('');const [editing,setEditing]=useState<Product|null|undefined>();const [form,setForm]=useState<Form>(blank);const [saving,setSaving]=useState(false);const load=useCallback(()=>api.get<ApiResponse<{products:Product[];pagination:PaginationType}>>(`/products?page=${page}&limit=10&search=${encodeURIComponent(search)}`).then(r=>{setProducts(r.data.data.products);setPagination(r.data.data.pagination)}),[page,search]);useEffect(()=>{load()},[load]);useEffect(()=>{api.get<ApiResponse<{categories:Category[]}>>('/categories').then(r=>setCategories(r.data.data.categories))},[])
const open=(p?:Product)=>{setEditing(p||null);setForm(p?{name:p.name,description:p.description,price:String(p.price),compareAtPrice:p.compareAtPrice?String(p.compareAtPrice):'',stock:String(p.stock),category:p.category._id,images:null}:blank)}
const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);const body=new FormData();Object.entries(form).forEach(([k,v])=>{if(k!=='images'&&v!==null&&v!=='')body.append(k,String(v))});if(form.images)Array.from(form.images).forEach(f=>body.append('images',f));try{if(editing)await api.patch(`/products/${editing._id}`,body);else await api.post('/products',body);toast.success(editing?'Product updated':'Product created');setEditing(undefined);load()}catch(err){toast.error(errorMessage(err))}finally{setSaving(false)}}
const remove=async(p:Product)=>{if(!confirm(`Remove ${p.name}?`))return;try{await api.delete(`/products/${p._id}`);toast.success('Product removed');load()}catch(e){toast.error(errorMessage(e))}}
const addCategory=async()=>{const name=prompt('New category name');if(!name)return;try{const r=await api.post<ApiResponse<{category:Category}>>('/categories',{name});setCategories(c=>[...c,r.data.data.category]);toast.success('Category created')}catch(e){toast.error(errorMessage(e))}}
return <><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-black/45">Catalog</p><h1 className="text-3xl font-black">Products</h1></div><div className="flex gap-2"><button onClick={addCategory} className="btn-secondary">New category</button><button onClick={()=>open()} className="btn-primary"><Plus size={17}/> Add product</button></div></div><div className="card mt-7 overflow-hidden"><div className="border-b border-black/5 p-4"><div className="relative max-w-sm"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-black/35" size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} className="field !pl-10" placeholder="Search products"/></div></div><div className="overflow-x-auto"><table className="w-full min-w-180 text-left text-sm"><thead className="bg-[#fafaf8] text-xs uppercase tracking-wider text-black/40"><tr><th className="p-4">Product</th><th>Category</th><th>Price</th><th>Stock</th><th className="pr-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-black/5">{products.map(p=><tr key={p._id}><td className="p-4"><div className="flex items-center gap-3"><div className="size-12 overflow-hidden rounded-lg bg-cream">{p.images[0]&&<img src={mediaUrl(p.images[0].url)} className="h-full w-full object-cover"/>}</div><b>{p.name}</b></div></td><td>{p.category?.name}</td><td>{money(p.price)}</td><td><span className={p.stock<5?'font-bold text-red-600':''}>{p.stock}</span></td><td className="pr-4"><div className="flex justify-end gap-1"><button onClick={()=>open(p)} className="rounded-lg p-2 hover:bg-black/5"><Edit3 size={17}/></button><button onClick={()=>remove(p)} className="rounded-lg p-2 text-red-600 hover:bg-red-50"><Trash2 size={17}/></button></div></td></tr>)}</tbody></table></div>{pagination&&<div className="pb-5"><Pagination page={page} pages={pagination.pages} onChange={setPage}/></div>}</div>
{editing!==undefined&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/45 p-4"><div className="max-h-[92vh] w-full max-w-2xl overflow-auto rounded-3xl bg-white p-6 shadow-2xl sm:p-8"><div className="flex justify-between"><h2 className="text-2xl font-black">{editing?'Edit product':'Add product'}</h2><button onClick={()=>setEditing(undefined)}><X/></button></div><form onSubmit={submit} className="mt-6 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="label">Name</span><input required className="field" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="sm:col-span-2"><span className="label">Description</span><textarea required rows={4} className="field" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label><span className="label">Price</span><input required min="0" step="0.01" type="number" className="field" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label><span className="label">Compare-at price</span><input min="0" step="0.01" type="number" className="field" value={form.compareAtPrice} onChange={e=>setForm({...form,compareAtPrice:e.target.value})}/></label><label><span className="label">Stock</span><input required min="0" type="number" className="field" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/></label><label><span className="label">Category</span><select required className="field" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="">Select</option>{categories.map(c=><option value={c._id} key={c._id}>{c.name}</option>)}</select></label><label className="sm:col-span-2"><span className="label">Product images</span><input multiple accept="image/*" type="file" className="field" onChange={e=>setForm({...form,images:e.target.files})}/><span className="mt-1 block text-xs text-black/40">Up to 8 images, 5 MB each.</span></label><div className="mt-2 flex justify-end gap-2 sm:col-span-2"><button type="button" onClick={()=>setEditing(undefined)} className="btn-secondary">Cancel</button><button disabled={saving} className="btn-primary">{saving?'Saving…':'Save product'}</button></div></form></div></div>}</>}
